language: python
python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - git clone https://github.com/cspace-deployment/cspace-webapps-ucb ~/cspace-webapps-ucb

# command to run tests
script:
  - make test
  - coverage run manage.py test

after_script:
  coveralls
